import { google } from "googleapis";
import { TokenManager } from "../gmail/token-manager";
import { v4 as uuidv4 } from "uuid";

export class CalendarService {
  /**
   * Creates a Google Calendar event with a Google Meet link attached.
   */
  static async createMeetingEvent(
    userId: string,
    options: {
      summary: string;
      description?: string;
      startTime: string; // ISO string
      endTime: string;   // ISO string
      attendeeEmails: string[];
    }
  ) {
    const accessToken = await TokenManager.getValidAccessToken(userId);
    
    const auth = new google.auth.OAuth2();
    auth.setCredentials({ access_token: accessToken });

    const calendar = google.calendar({ version: "v3", auth });

    const event = {
      summary: options.summary,
      description: options.description || "Generated by Aura AI Assistant.",
      start: {
        dateTime: options.startTime,
        timeZone: "UTC", // In a real app we'd resolve the user's timezone
      },
      end: {
        dateTime: options.endTime,
        timeZone: "UTC",
      },
      attendees: options.attendeeEmails.map(email => ({ email })),
      conferenceData: {
        createRequest: {
          requestId: uuidv4(),
          conferenceSolutionKey: {
            type: "hangoutsMeet"
          }
        }
      }
    };

    try {
      const res = await calendar.events.insert({
        calendarId: "primary",
        conferenceDataVersion: 1,
        sendUpdates: "all",
        requestBody: event,
      });

      return {
        eventId: res.data.id,
        meetLink: res.data.hangoutLink,
        htmlLink: res.data.htmlLink,
      };
    } catch (error: any) {
      console.error("Error creating Google Calendar event:", error);
      throw new Error(`Failed to create calendar event: ${error.message}`);
    }
  }
}
